language: python
python:
  - "3.7"
  - "nightly"
jobs:
  allow_failures:
    - python: "nightly"
install:
  - pip install -U setuptools
  - pip install -e .
  - pip install -e .[dev]
script:
  - nosetests
  - python setup.py sdist bdist_wheel && pip install dist/ovh-*.tar.gz && cd /tmp && python -c 'import ovh; ovh.Client("ovh-eu").get("/auth/time", _need_auth=False)' && cd -
deploy:
  provider: pypi
  user: $pypiUser
  password: $pypiPassword
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
    python: '3.7'
after_success:
    coveralls
sudo: false
